name:  build for android based kivy application
on:
    push:
        branches:
             - main
    release:
        types: [published]

jobs:
    android-build:
        runs-on: ubuntu-latest
        env:
            APP_ANDROID_ARCH: armeabi-v7a
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
                python-version: '3.10'

          - name: install dependencies
            run: pip3 install -r requirements.txt
          - name: Build with Buildozer
            uses: ArtemSBulgakov/buildozer-action@v1
            id: buildozer
            with:
                workdir: .
                buildozer_version: stable
          
          - name: Upload artifacts
            id: upload
            uses: actions/upload-artifact@v2    
            with:
                name: app_artifacts
                path: ${{ steps.buildozer.outputs.filename }}
          - name: Echo Buildfile
            run: | 
                echo ${{steps.upload.outputs}}
                echo ${{steps.buildozer.outputs.filename}}
