name:  build for android based kivy application
on:
    release:
        types: [published]

jobs:
    android-build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: install dependencies
            run: pip3 install -r requirements.txt
            