name: releaseEvent

on:
    release:
        types: [published]

jobs:
    release_job:
        needs: build_job
        if: success()
        runs-on: ubuntu-latest
        steps:
            - name: deployment_is_going_on
              run: |
               echo "RELEASING ..."
               echo "AFTER BUILD"

    build_job:
        runs-on: ubuntu-latest
        steps:
            - name:  "Building"
              if: "${{contains(github.event_name, 'release')}} == \"true\""
              run: echo "Building ...."
