name: Learning Environment secrets


on:
  push:
    branches:
      - main

jobs:
  develop:
    runs-on: ubuntu-latest
    env:
      MY_TOKEN: ${{secrets.PYPI_USER}}
      PROJECT: "THIS IS GUNA"
    steps:
      - name: development enviroment
        with:
          environment: development
          token: ${{secrets.USERNAME}}
        run: |
          echo "${{secrets.USERNAME}}"
          echo "$MY_TOKEN"
          echo $PROJECT
          
      - name: ECHO SECRESTS
        run: echo "SECRETS.yml"
        
  release:
    runs-on: ubuntu-lastest
    steps:
      - name: Release Environment
        with:
          environment: release
          token: ${{secrets.USER_NAME}}
        run: echo "RELEASE RUNNING"
      
